"""add campaigns and campaign_npcs

Revision ID: 00fbba73de6a
Revises: f9e073cc94a4
Create Date: 2026-02-21 18:13:33.532381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fbba73de6a'
down_revision: Union[str, Sequence[str], None] = 'f9e073cc94a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_npcs',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'npc_id')
    )
    op.add_column('campaigns', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'owner_id')
    op.drop_table('campaign_npcs')
    # ### end Alembic commands ###
