"""add campaign fields

Revision ID: f161f87d9ac8
Revises: 00fbba73de6a
Create Date: 2026-02-21 18:35:16.048182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f161f87d9ac8'
down_revision: Union[str, Sequence[str], None] = '00fbba73de6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='campaignstatus'), nullable=True))
    op.add_column('campaigns', sa.Column('current_session', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('location', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('session_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'session_notes')
    op.drop_column('campaigns', 'location')
    op.drop_column('campaigns', 'current_session')
    op.drop_column('campaigns', 'status')
    # ### end Alembic commands ###
